[package]
name = "ch14"  
version = "0.1.0"
edition = "2021" 

[[bin]]
name = "generic"
path = "generic.rs"

[[bin]]
name = "function"
path = "function.rs"

[[bin]]
name = "implementation"
path = "implementation.rs"

[[bin]]
name = "trait"
path = "trait.rs"