[package]
name = "ch9"  
version = "0.1.0"
edition = "2021"  

[[bin]]
name = "visibility"
path = "visibility.rs"

[[bin]]
name = "struct_visibility"
path = "struct_visibility.rs"

[[bin]]
name = "use"
path = "use.rs"

[[bin]]
name = "super_and_self"
path = "super_and_self.rs"